apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
data:
  postgres_user: {{ .Values.postgresUser | b64enc | quote }}
  postgres_password: {{ .Values.postgresPassword | b64enc | quote }}
