apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database
        - name: MONGO_HOST
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: host
        - name: MONGO_INITDB_ROOT_USERNAME  
          valueFrom:
            secretKeyRef:
              name: mongodb-secret 
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---