apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
data:
  mongo-root-username: {{ .Values.mongodbUser | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodbPassword | b64enc | quote }}